server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth {
        proxy_pass http://auth-service:3001;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /api/products {
        proxy_pass http://product-service:3000;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /api/cart {
        proxy_pass http://product-service:3000;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /api/orders {
        proxy_pass http://order-service:3002;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }
}
